version: 2
defaults:
  working_directory: ~/app
  docker:
    - image: 'cypress/base:8'
      environment:
        TERM: xterm
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: 'cypress/base:8'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: npm install
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app
  test1:
    working_directory: ~/app
    docker:
      - image: 'cypress/base:8'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests 1
          command: $(npm bin)/cypress run --spec cypress/integration/sample1.spec.js --reporter mochawesome --reporter-options "reportFilename=sample1"
      - persist_to_workspace:
          root: reports
          paths:
            - sample1.json
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: Install python
          command: sudo apt-get install -y python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: S3 Upload
          command: >
            aws s3 cp ~/app/reports/mochawesome.json s3://$BUCKET_NAME/builds/
            --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}
  test2:
    working_directory: ~/app
    docker:
      - image: 'cypress/base:8'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests 1
          command: $(npm bin)/cypress run --spec cypress/integration/sample1.spec.js --reporter mochawesome --reporter-options "reportFilename=sample2"
      - persist_to_workspace:
          root: reports
          paths:
            - sample2.json
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: Install python
          command: sudo apt-get install -y python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: S3 Upload
          command: >
            aws s3 cp ~/app/reports/mochawesome.json s3://$BUCKET_NAME/builds/
            --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}
  test3:
    working_directory: ~/app
    docker:
      - image: 'cypress/base:8'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests 3
          command: $(npm bin)/cypress run --spec cypress/integration/sample1.spec.js --reporter mochawesome --reporter-options "reportFilename=sample3"
      - persist_to_workspace:
          root: reports
          paths:
            - sample3.json
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: Install python
          command: sudo apt-get install -y python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: S3 Upload
          command: >
            aws s3 cp ~/app/reports/mochawesome.json s3://$BUCKET_NAME/builds/
            --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}
  downstream:
    working_directory: ~/app
    docker:
      - image: 'cypress/base:8'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: /app/reports
      - run: ls /app/reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - downstream:
          requires:
            - test1
            - test2
            - test3
